/* CityProject.java  -- project class file with the project's main method   
 *  
 * This software package creates a graph of cities in the Unitied States with
 * links between the cities. Each city is a vertex in the graph.
 * Each link between cities is an edge in the graph.   The data for the cities and
 * links are read into arrays from data files, which should be in the project folder.
 * The files are CSV files, which can be read and edited in Excel.
 *
 * The main class for the project is the CityProject class.   Other class include:
 * 
 *   Vertex - clas for each Vertex in a graph.
 *   City extends Vertex - Each City is a Vertex with added properties.  Each City
 *      has a unique name, and X and Y cooordinates for location on a 1500 by 900 Canvas.
 *   Edge - an edge in the graph, with a source, destination, and length.
 *   AjacencyNode - a node for a linked list of cities directly connected to each City.
 *      Each City has a linked list of adjacnt cities, created from the info in the 
 *      data files, with destination City and distance data in the node, and a 
 *      link to the next node. 
 *   CityMap - extends Canvas, a map of the graph on a 1500 by 900 GUI Canvas.
 *      A CityMap object in instantiated in the drawMap method in the CityProject class.
 *
 * * * * * * ADDED CLASSES * * * * * * * * * * *  ADDED CLASSES * * * * * * * * * * *
 *
 *   Interface - this class holds all of the data provided by the main class, including
 *      the JFrame generated by the CityMap class. This class is where all of the code
 *      for DIJKSTRA'S ALGORITHM is.
 *   CityStack - this class is to hold the data generated by Dijkstra's Algorithm.
 *      It is also used in the paint method inside of the CityMap class.
 * 
 * The main method in the CityProject class calls methods to reads City and Edge 
 * data from data files into arrays, set up the adjacency list in each instance 
 * of City, print a list of Vertex cities and their Edges, then draw a map of the graph.
 *
 * created for use by students in CSCI 211 at Community Colle of Philadelphia
 * copyright 2014 by C. herbert.  last edited Nov. 23, 2014 by C. Herbert
 */

/* * * *Changes Made to data files * * * *
 * * File: cities.csv * *
 * San Diego CA,318,476 to San Diego CA,325,490
 * ADDED:
 * Oceanside CA,311,470
 *
 * * File: links.csv
 * ADDED:
 * Oceanside CA,San Diego CA,27     -and- vice versa
 * Oceanside CA,Los Angeles CA,102  -and- vice versa
 * Oceanside CA,Yuma AZ,154         -and- vice versa
 * Oceanside CA,Las Vegas NV,302    -and- vice versa
 */

package cityproject;

import java.awt.*;
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CityProject {


    // main metod for the project
    public static void main(String[] args) {

        City[] cities = new City[200]; //array of cities (Vertices) max = 200
        for (int i = 0; i < cities.length; i++) {
            cities[i] = new City();
        } // end for

        Edge[] links = new Edge[2000];// array of links  (Edges)  max = 2000
        for (int i = 0; i < links.length; i++) {
            links[i] = new Edge();
        } // end for

        int cityCount; //    actual number of cities
        int linkCount; //    actual number of links

        // load cities into an array from a datafile
        cityCount = readCities(cities);
        // load links into an array from a datafile
        linkCount = readLinks(links, cities);
        // create the adjacency list for each city based on the link array
        createAdjacencyLists(cityCount, cities, linkCount, links);
        ; 
        
        // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
        // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
        // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
        
        // Starts User Interface and draw the map and links
        startUserInterface(cities, cityCount, linkCount, links);
        
        
    } // end main
    //************************************************************************

    
    
    // method to read city data into an array from a data file
    public static int readCities(City[] cities) {

        int count = 0; // number of cities[] elements with data

        String[][] cityData = new String[124][3]; // holds data from the city file 
                                                  // MUST MATCH NUMBER OF LINES IN cities.csv
                                                  
        String delimiter = ",";                   // the delimiter in a csv file
        String line;                              // a String to hold each line from the file
        
        String fileName = "cities.csv";           // the file to be opened  

        try {
            // Create a Scanner to read the input from a file
            Scanner infile = new Scanner(new File(fileName));

            /* This while loop reads lines of text into an array. it uses a Scanner class 
             * boolean function hasNextLine() to see if there is another line in the file.
             */
            while (infile.hasNextLine()) {
                // read the line 
                line = infile.nextLine();

                // split the line into separate objects and store them in a row in the array
                cityData[count] = line.split(delimiter);
                
                // read data from the 2D array into an array of City objects
                cities[count].setName(cityData[count][0]);
                cities[count].setX(Integer.parseInt(cityData[count][1]));
                cities[count].setY(Integer.parseInt(cityData[count][2]));

                count++;
            }// end while

            infile.close();

        } catch (IOException e) {
            // error message dialog box with custom title and the error icon
            JOptionPane.showMessageDialog(null, "File I/O error:" + fileName, "File Error", JOptionPane.ERROR_MESSAGE);
        }
        return count;

    } // end loadCities()
    //*************************************************************************

    // method to read link data into an array from a data file
    public static int readLinks(Edge[] links, City[] cities) {
        int count = 0; // number of links[] elements with data

        String[][] CityLinkArray = new String[702][3]; // holds data from the link file
                                                       // MUST MATCH NUMBER OF LINES IN links.csv
        String delimiter = ",";                       // the delimiter in a csv file
        String line;				      // a String to hold each line from the file

        String fileName = "links.csv";                // the file to be opened  

        try {
            // Create a Scanner to read the input from a file
            Scanner infile = new Scanner(new File(fileName));

            /* This while loop reads lines of text into an array. it uses a Scanner class 
             * boolean function hasNextLine() to see if there another line in the file.
             */
            while (infile.hasNextLine()) {
                
                // read the line 
                line = infile.nextLine();

                // split the line into separate objects and store them in a row in the array
                CityLinkArray[count] = line.split(delimiter);

                // read link data from the 2D array into an array of Edge objects
                // set source to vertex with city name in source column
                links[count].setSource(findCity(cities, CityLinkArray[count][0]));
                // set destination to vertex with city name in destination column
                links[count].setDestination(findCity(cities, CityLinkArray[count][1]));
                //set length to integer valuein length column
                links[count].setLength(Integer.parseInt(CityLinkArray[count][2]));

                count++;

            } // end while

        } catch (IOException e) {
            // error message dialog box with custom title and the error icon
            JOptionPane.showMessageDialog(null, "File I/O error:" + fileName, "File Error", JOptionPane.ERROR_MESSAGE);
        } // try/catch block
        return count;
    } // end readLinks()
    //*************************************************************************

    // method to find the City object with the given city name
    public static City findCity(City[] cities, String n) {
        int index = 0;  // loop counter
        
        // go through the cities array until the name is found
        while (cities[index].getName().compareTo(n) != 0)
            index++;
        
        return cities[index];

    } // end  findCity()

// method to create an adjacency lists for each city
    public static void createAdjacencyLists(int cityCount, City[] cities, int linkCount, Edge[] links) {

        AdjacencyNode temp = new AdjacencyNode();

        // iterate city array
        for (int i = 0; i < cityCount; i++) {

            //iterate link array
            for (int j = 0; j < linkCount; j++) {
                // if the currentl link's source is the current city
                if (links[j].getSource() == cities[i]) {

                    /* create a node for the link and inseert it into the adjancency list
                     * as the new head of the list. 
                     */
                    // temporarily store the current value of the list's head
                    temp = cities[i].getAdjacencyListHead();
                    //create a new node
                    AdjacencyNode newNode = new AdjacencyNode();
                    // add city and distance data
                    newNode.setCity(links[j].getDestination());
                    newNode.setDistance(links[j].getLength());
                    // point newNode to the previous list head
                    newNode.setNext(temp);

                    // set the new head of the list to newNode
                    cities[i].setAdjacencyListHead(newNode);

                }  // end if
            } // end for j
        } // end for i
    } // end createAdjacencyLists()

    // method to print adjacency lists - NO LONGER USED
    public static void PrintAdjacencyLists(int cityCount, City[] cities) {

        System.out.println("List of Edges in the Graph of Cities by Source City");
        // iterate array of cities
        for (int i = 0; i < cityCount; i++) {

            // set current to adjacency list for this city    
            AdjacencyNode current = cities[i].getAdjacencyListHead();

            // print city name
            System.out.println("\nFrom " + cities[i].getName());

            // iterate adjacency list and print each node's data
            while (current != null) {
                System.out.println("\t"+ current.toString());
                current = current.getNext();
            } // end while (current != null) 
        } // end for i 
    } // end PrintAdjacencyLists()
    
    // method to draw the graph (map of cities and links)
   static JFrame drawMap(int cCount, City[] c, int lCount, Edge[] l){
       
       CityMap canvas1 = new CityMap(cCount, c, lCount, l, null);

        int width = 1500; // width of the Canvas
        int height = 900; // heightof the Canvas 
        
        // set up a JFrame to hold the canvas
        JFrame mapWindow = new JFrame();
        mapWindow.setTitle("U.S. Cities");
        mapWindow.setSize(width, height);
        mapWindow.setLocation(10, 10);
        mapWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // add the canvas to the mapWindow as a content panel
        mapWindow.getContentPane().add(canvas1);
        mapWindow.setVisible(true);
        
        return mapWindow;

   } // end drawMap()
   
   /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    * * * NEW METHODS FOR ASSIGNMENT  * * * * NEW METHODS FOR ASSIGNMENT* * * * 
    * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

   static void startUserInterface(City[] cities, int cityCount, int linkCount, Edge[] links){
       
       JFrame mapWindow = drawMap(cityCount, cities, linkCount, links);
       
       // instantiate new array the size of non-null elements of the cities array
       // and copy city array to new array with size of the amount of non-null indecies
       City[] actualCities = new City[cityCount];
       System.arraycopy(cities, 0, actualCities, 0, cityCount);
       
       Interface inputWindow = new Interface(cityCount, actualCities, linkCount, links, mapWindow);
       inputWindow.setVisible(true);
       
   } // end startUserInterface method
   
} // end class cityProject
